import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JP Quintana | PortFolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-950`}>
        {/* circle */}
        {/* <div className="bg-slate-100 w-[400px] h-[400px] rounded-[100%] absolute top-0 left-[-150px] blur-lg opacity-10"></div> */}
        {/* <div className="bg-slate-100 w-[400px] h-[400px] rounded-[100%] absolute top-[400px] left-[-150px] blur-lg opacity-10"></div> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
